Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [5]:
NAME = ""
COLLABORATORS = ""

---

Euclidean spaces : exercises
======

Implement the following functions with `numpy`

In [6]:
from math import sqrt
import numpy as np


def norm(x):
    """
    Args:
      x (np.array): vector
    Returns:
      float. the norm of x
    """
    return sqrt(x.transpose()@x)
    

def distance(x,y):
    """
    Args:
       x (np.array): vector
       y (np.array): vector
    Returns:
       float. the euclidean distance between x and y
    """
    return sqrt((x-y).transpose()@(x-y))

def similarity(x,y):
    """
    Args:
       x (np.array): vector
       y (np.array): vector
    Returns:
	float. the cosine of the angle between x and y
    """
    # YOUR CODE HERE
    return (x.transpose()@y)/(norm(x)*norm(y))

def is_orthogonal(x,y):
    """
    Args:
       x (np.array): vector
       y (np.array): vector
    Returns:
	bool. True if x and y are orthogonal, False otherwise.
    """
    # YOUR CODE HERE
    return similarity(x, y) == 0



Euclidean spaces
====

Use numpy or the functions you defined above to solve the following exercises.
Check manually that your solutions are correct.

In [14]:
# Vectors and distances

x = np.array([-1,5,2])
y = np.array([3,1,1])

sum_vector = x+y
print(sum_vector)

diff_vector = x-y
print(diff_vector)

# Compute x / ||x||
print(x/norm(x))

# Compute || 0.5(x-y)||
print(norm(0.5*(x-y)))

# Compute || 0.5(x+y)||
print(norm(0.5*(x+y)))


# Compute x - 2y
print(x - 2*y)

# Does || x-y || = ||x|| - ||y|| ?
print(distance(x, y) == norm(x)-norm(y))


# Does || x+y || = ||x|| + ||y|| ?
print(norm(x+y) == norm(x)-norm(y))


[2 6 3]
[-4  4  1]
[-0.18257419  0.91287093  0.36514837]
2.8722813232690143
3.5
[-7  3  0]
False
False


In [ ]:
# Angles

#Compute the angle (in degrees) between x and y

from math import pi
from numpy import cos, degrees, rad2deg


x = np.array([5,1,-2], float)
y = np.array([4,-4,3], float)

# YOUR CODE HERE
print(degrees(similarity(x, y)))

#Compute the angle (in degrees) between x and y
x = np.array([7,2,-10])
y = np.array([2,6,4])

# YOUR CODE HERE
print(degrees(similarity(x, y))) #We can add 2pi to be sure of a positive radiants


#Are x and y orthogonal ?

x = np.array([8,4,3])
y = np.array([-2,1,4])

# YOUR CODE HERE
print(is_orthogonal(x, y))

#Are x and y orthogonal ?

x = np.array([6,0,4])
y = np.array([0,2,-1])

print(is_orthogonal(x, y))

# Check Cauchy Schwarz is  true on the example:
x = np.array([2,1,4])
y = np.array([1,-2,0])

print(x.transpose().dot(y)<=(norm(x)*norm(y)))

#Also check that the triangle inequality is true
print(norm(x+y)<=norm(x)+norm(y))


# Check Cauchy Schwarz is  true on the example:
x = np.array([4,2,-1])
y = np.array([8,4,-2])

# YOUR CODE HERE
print(x.transpose().dot(y)<=(norm(x)*norm(y)))

#Also check that the triangle inequality is true
# YOUR CODE HERE
print(norm(x+y)<=norm(x)+norm(y))


16.336916024886914


TypeError: math.cos() takes exactly one argument (2 given)